In [1]:
import pandas as pd

In [13]:
import pandas as pd

pd.options.display.float_format = '{:,.1f}'.format  # 정수처럼 천 단위 쉼표 붙이기

In [14]:
df = pd.read_csv("/Users/yiji/Desktop/ybigta/project/교육 공모전/Contest_edudata/Database/schoolinfo/summary/combined_summary/combined_예산_세출_합계요약.csv")
df

,파일명,인적자원_운용,학생복지_교육격차해소,기본적_교육활동,선택적_교육활동,교육활동_지원,학교_일반운영,학교_시설확충,학교_재무활동,1인당 평균 세출,평균합계,학교급
0,고등_예산_세출_2024.csv,"4,309,777,718,000.0","2,038,253,146,000.0","769,244,746,000.0","319,073,215,000.0","343,367,608,000.0","999,846,429,000.0","192,790,682,000.0","18,689,410,000.0","20,753,647,449.8","9,011,796,601,449.8",고등
1,고등_예산_세출_2022.csv,"4,263,275,177,349.0","1,726,123,350,564.0","508,101,233,948.0","321,645,096,163.0","304,311,305,761.0","849,772,581,154.0","129,382,375,780.0","22,568,546,000.0","18,883,194,094.8","8,144,062,860,813.8",고등
2,고등_예산_세출_2023.csv,"4,248,315,254,000.0","1,873,428,534,000.0","644,183,537,000.0","304,070,822,000.0","338,987,618,000.0","910,809,158,000.0","185,112,198,000.0","20,151,774,000.0","20,015,943,312.8","8,545,074,838,312.8",고등
3,중등_예산_세출_2024.csv,"1,605,941,581,000.0","1,369,992,501,000.0","539,833,793,000.0","180,912,820,000.0","267,292,031,000.0","804,627,718,000.0","40,712,114,000.0","5,426,415,000.0","23,640,131,142.7","4,838,379,104,142.7",중등
4,중등_예산_세출_2022.csv,"1,589,341,377,000.0","1,116,130,974,000.0","407,292,699,000.0","165,783,907,000.0","260,439,024,000.0","696,096,296,000.0","41,631,277,000.0","8,840,550,000.0","20,348,422,908.9","4,305,904,526,908.9",중등
5,중등_예산_세출_2023.csv,"1,572,791,240,000.0","1,234,849,841,000.0","474,845,789,000.0","166,452,074,000.0","267,872,418,000.0","734,313,771,000.0","42,244,625,000.0","5,851,937,000.0","22,365,206,909.2","4,521,586,901,909.2",중등
6,초등_예산_세출_2024.csv,"317,722,000,000.0","2,431,297,603,000.0","952,278,398,000.0","1,218,948,484,000.0","447,977,853,000.0","1,524,850,711,000.0","58,737,478,000.0","12,246,354,000.0","39,016,408,335.4","7,003,075,289,335.4",초등
7,초등_예산_세출_2022.csv,"357,259,830,000.0","2,018,870,612,000.0","812,287,862,000.0","1,112,771,905,000.0","434,863,947,000.0","1,266,955,579,000.0","40,837,450,000.0","15,303,130,000.0","29,793,584,032.8","6,088,943,899,032.8",초등
8,초등_예산_세출_2023.csv,"309,741,215,000.0","2,228,818,464,000.0","931,082,775,000.0","1,155,440,875,000.0","456,299,775,000.0","1,374,839,972,000.0","51,854,310,000.0","13,374,337,000.0","34,718,575,943.3","6,556,170,298,943.3",초등
9,combined_예산_세출_초등_합계,"984,723,045,000.0","6,678,986,679,000.0","2,695,649,035,000.0","3,487,161,264,000.0","1,339,141,575,000.0","4,166,646,262,000.0","151,429,238,000.0","40,923,821,000.0","103,528,568,311.5","19,648,189,487,311.5",초등
10,combined_예산_세출_중등_합계,"4,768,074,198,000.0","3,720,973,316,000.0","1,421,972,281,000.0","513,148,801,000.0","795,603,473,000.0","2,235,037,785,000.0","124,588,016,000.0","20,118,902,000.0","66,353,760,960.8","13,665,870,532,960.8",중등
11,combined_예산_세출_고등_합계,"12,821,368,149,349.0","5,637,805,030,564.0","1,921,529,516,948.0","944,789,133,163.0","986,666,531,761.0","2,760,428,168,154.0","507,285,255,780.0","61,409,730,000.0","59,652,784,857.4","25,700,934,300,576.4",고등
12,2024_합계,"6,233,441,299,000.0","5,839,543,250,000.0","2,261,356,937,000.0","1,718,934,519,000.0","1,058,637,492,000.0","3,329,324,858,000.0","292,240,274,000.0","36,362,179,000.0","83,410,186,927.9","20,853,250,994,927.9",NaN
13,2022_합계,"6,209,876,384,349.0","4,861,124,936,564.0","1,727,681,794,948.0","1,600,200,908,163.0","999,614,276,761.0","2,812,824,456,154.0","211,851,102,780.0","46,712,226,000.0","69,025,201,036.5","18,538,911,286,755.5",NaN
14,2023_합계,"6,130,847,709,000.0","5,337,096,839,000.0","2,050,112,101,000.0","1,625,963,771,000.0","1,063,159,811,000.0","3,019,962,901,000.0","279,211,133,000.0","39,378,048,000.0","77,099,726,165.3","19,622,832,039,165.3",NaN

In [15]:
df[df["파일명"] == "2023_합계"]

,파일명,인적자원_운용,학생복지_교육격차해소,기본적_교육활동,선택적_교육활동,교육활동_지원,학교_일반운영,학교_시설확충,학교_재무활동,1인당 평균 세출,평균합계,학교급
14,2023_합계,"6,130,847,709,000.0","5,337,096,839,000.0","2,050,112,101,000.0","1,625,963,771,000.0","1,063,159,811,000.0","3,019,962,901,000.0","279,211,133,000.0","39,378,048,000.0","77,099,726,165.3","19,622,832,039,165.3",NaN

In [16]:
df2 = df[["파일명","학교_일반운영", "학교_시설확충", "학교_재무활동"]]
df2[df2["파일명"] == "2023_합계"]

        파일명             학교_일반운영           학교_시설확충          학교_재무활동
14  2023_합계 3,019,962,901,000.0 279,211,133,000.0 39,378,048,000.0

In [17]:
import os
import pandas as pd

# 경로 설정
base_path = "/Users/yiji/Desktop/ybigta/project/교육 공모전/Contest_edudata/Database/schoolinfo/summary/combined_summary"

# 결과를 누적할 리스트
results = []

# 지역별 디렉토리 순회
for region in os.listdir(base_path):
    region_path = os.path.join(base_path, region)
    
    # 폴더인지 확인 (파일명들과 구분)
    if os.path.isdir(region_path):
        target_file = os.path.join(region_path, "combined_예산_세출_합계요약.csv")
        
        if os.path.exists(target_file):
            df = pd.read_csv(target_file)
            # 원하는 컬럼만 추출 + 필터링
            df_filtered = df[df["파일명"] == "2023_합계"][["파일명", "학교_일반운영", "학교_시설확충", "학교_재무활동"]]
            # 지역명 추가
            df_filtered["지역"] = region
            results.append(df_filtered)

# 결과 합치기
final_df = pd.concat(results, ignore_index=True)

# 결과 저장 (선택)
final_df.to_csv("지역별_예산_세출_합계요약_2023.csv", index="파일명")

# 결과 확인
print(final_df)

        파일명           학교_일반운영          학교_시설확충          학교_재무활동          지역
0   2023_합계 121,421,336,000.0  1,889,643,000.0  3,882,093,000.0    인천광역시교육청
1   2023_합계 177,825,893,000.0 25,717,225,000.0  1,767,097,000.0    부산광역시교육청
2   2023_합계  26,588,146,000.0    221,000,000.0    139,052,000.0  세종특별자치시교육청
3   2023_합계 103,675,690,000.0  4,349,940,000.0    947,689,000.0    대구광역시교육청
4   2023_합계 128,509,771,000.0 32,630,296,000.0  1,953,024,000.0  전북특별자치도교육청
5   2023_합계 137,279,000,000.0 10,909,680,000.0  2,811,395,000.0     전라남도교육청
6   2023_합계  84,122,522,000.0 44,748,430,000.0    746,262,000.0    광주광역시교육청
7   2023_합계  64,016,851,000.0 14,367,423,000.0  1,109,651,000.0    울산광역시교육청
8   2023_합계 198,449,290,000.0 14,952,745,000.0    484,290,000.0     경상북도교육청
9   2023_합계  45,063,607,000.0  2,123,599,000.0    452,746,000.0  제주특별자치도교육청
10  2023_합계 233,522,489,000.0 23,568,636,000.0  3,479,800,000.0     경상남도교육청
11  2023_합계  90,079,498,000.0  1,870,541,000.0  1,046,514,000.0    대전광역시교육청
12  2023_합계 744,403,079,000.0 11,996,437,000.0  3,691,252,000.0      경기도교육청
13  2023_합계 114,769,935,000.0  6,913,527,000.0  1,229,687,000.0  강원특별자치도교육청
14  2023_합계 165,535,729,000.0  2,885,410,000.0  1,549,024,000.0     충청남도교육청
15  2023_합계 466,998,892,000.0 69,935,589,000.0 12,887,884,000.0    서울특별시교육청
16  2023_합계 117,701,173,000.0 10,131,012,000.0  1,200,588,000.0     충청북도교육청

# 결과 보고서 뉴스 예산 계산

In [3]:
import pandas as pd

file_path = "news_report.csv"

# 🚨 구분자 자동 설정: 탭으로 구분
df = pd.read_csv(file_path, sep="\t")

# 열 이름 공백 제거
df.columns = df.columns.str.strip()

# 열 이름 확인
print("📌 열 이름 목록:", df.columns.tolist())

# 열 이름 직접 지정
예산금액_열 = "예산금액"
다음예산_열 = "다음연도예산"
비율_열 = "비율"
다음비율_열 = "다음연도비율"

# 숫자형 변환
df[예산금액_열] = pd.to_numeric(df[예산금액_열], errors="coerce")
df[다음예산_열] = pd.to_numeric(df[다음예산_열], errors="coerce")

# 전체 합
total_current = df[예산금액_열].sum()
total_next = df[다음예산_열].sum()

# 비율 계산
df[비율_열] = (df[예산금액_열] / total_current * 100).round(2)
df[다음비율_열] = (df[다음예산_열] / total_next * 100).round(2)

# 저장
df.to_csv("news_report_with_ratio.csv", index=False)
print("✅ 비율 계산 및 저장 완료!")

📌 열 이름 목록: ['대분류', '예산금액', '비율', 'RFC_점수', '증감율', '다음연도예산', '다음연도비율']
✅ 비율 계산 및 저장 완료!

In [4]:
df = pd.read_csv("news_report_with_ratio.csv")
df

           대분류          예산금액     비율    RFC_점수       증감율        다음연도예산  다음연도비율
0       인적자원운용  6.233441e+12  30.48  0.470070 -0.255551  6.217512e+12   30.35
1  학생복지/교육격차해소  5.839543e+12  28.55  0.503856  0.516713  5.869717e+12   28.65
2      기본적교육활동  2.261357e+12  11.06  0.491028  0.223500  2.266411e+12   11.06
3      선택적교육활동  1.718935e+12   8.41  0.496791  0.355226  1.725041e+12    8.42
4       교육활동지원  1.058637e+12   5.18  0.525990  1.022622  1.069463e+12    5.22
5       학교일반운영  3.019963e+12  14.77  0.000000  0.000000  3.019963e+12   14.74
6       학교시설확충  2.792111e+11   1.37  0.000000  0.000000  2.792111e+11    1.36
7       학교재무활동  3.937805e+10   0.19  0.000000  0.000000  3.937805e+10    0.19